# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b30f5736295117b892c45cbaf474ad52fad7e8d91e85b2fef77a73732c05f5bd25e85e6efd321ea27e0ef9a36a09155ad2826ebd553932b800c13a0b88b283c8

test:
  secret_key_base: 05d07229c0e281ec2b723fde3b3a333719e9239f3f27c7f5568b228f4cd9cc5d0e30e21279434feca5fde4e76167c4e865a75907ff822bf8c3a39be138a0e273

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
